[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
size = 12.0

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[terminal]
shell = { program = "/home/bergerj/.dotfiles/startup.sh", args = [] }

[keyboard]
bindings = [ 
    { key = "Return", mods = "Shift", chars = "\n" },
    { key = "Back", mods = "Control", chars = "\u0017" }
]
